"""In-context examples for IR generation prompts."""

from __future__ import annotations


def build_ir_generation_in_context_examples() -> str:
    """Return in-context examples used by IR-generation prompt."""
    return (
        "Example 1:\n"
        "Allowed roles and multiplicities: victim=1\n"
        "Extraction notes:\n"
        "The sentence describes a fatal incident. "
        "The victim is clearly identified as a local shopkeeper. "
        "No other explicit role spans are given.\n"
        "Output:\n"
        "arguments.victim += a local shopkeeper\n"
        "\n"
        "Example 2:\n"
        "Allowed roles and multiplicities: attacker=1, target=1, place=1\n"
        "Extraction notes:\n"
        "The sentence describes an attack. "
        "The attacker is clearly identified as rebel fighters. "
        "The target is a police outpost. "
        "The place is stated as the northern district of Halmin. "
        "The notes also mention rising tensions in the region, which is background context and not an argument.\n"
        "Output:\n"
        "arguments.attacker += rebel fighters\n"
        "arguments.target += a police outpost\n"
        "arguments.place += the northern district of Halmin\n"
        "\n"
        "Example 3:\n"
        "Allowed roles and multiplicities: attacker=1, target=3, instrument=2\n"
        "Extraction notes:\n"
        "The sentence reports an assault. "
        "The attacker is clearly identified as government troops. "
        "Three targets are explicitly mentioned: the radio station, the central market, and a nearby warehouse. "
        "Two instruments are explicitly described: mortars and heavy machine guns. "
        "The notes also mention panic among residents, which is a consequence and not an argument.\n"
        "Output:\n"
        "arguments.attacker += government troops\n"
        "arguments.target += the radio station\n"
        "arguments.target += the central market\n"
        "arguments.target += a nearby warehouse\n"
        "arguments.instrument += mortars\n"
        "arguments.instrument += heavy machine guns\n"
        "\n"
        "Example 4:\n"
        "Allowed roles and multiplicities: attacker=1, target=1, instrument=1, place=1\n"
        "Extraction notes:\n"
        "The sentence describes a bombing. "
        "The attacker is clearly identified as an unidentified militant cell. "
        "The target is a commuter bus. "
        "The place is given as the eastern entrance of the capital. "
        "No explicit instrument span is stated in the sentence. "
        "The notes also discuss earlier security warnings, which are background context and not arguments.\n"
        "Output:\n"
        "arguments.attacker += an unidentified militant cell\n"
        "arguments.target += a commuter bus\n"
        "arguments.place += the eastern entrance of the capital\n"
        "\n"
        "Example 5:\n"
        "Allowed roles and multiplicities: person.name=1, person.title=1, organization=1\n"
        "Extraction notes:\n"
        "The sentence identifies a person involved in the event. "
        "The person's name is Dr. Leoran Vesk. "
        "The person's title is chief medical officer. "
        "The associated organization is North Harbor General Hospital. "
        "The notes also mention public concern after the event, which is explanatory context and not an argument.\n"
        "Output:\n"
        "arguments.person.name += Dr. Leoran Vesk\n"
        "arguments.person.title += chief medical officer\n"
        "arguments.organization += North Harbor General Hospital\n"
        "\n"
        "Example 6:\n"
        "Allowed roles and multiplicities: attacker=1, target=1, place=1\n"
        "Extraction notes:\n"
        "The sentence does not provide any explicit valid argument span for the event. "
        "The notes mention speculation about who might have been involved and where it may have happened, "
        "but nothing is clearly supported. "
        "No explicit attacker, target, or place span can be extracted.\n"
        "Output:\n"
    )
