"""In-context examples for IR generation prompts."""

from __future__ import annotations


def build_ir_generation_in_context_examples() -> str:
    """Return in-context examples used by IR-generation prompt."""
    return (
        "Example 1:\n"
        "Allowed roles and multiplicities: victim=1, place=1\n"
        "Extraction notes:\n"
        "The sentence suggests a possible fatal incident, though the exact event type is not explicitly stated. "
        "The victim is not clearly identified; the text refers to people who may have been affected, but this is speculative and not confirmed. "
        "The place is clearly mentioned as the coastal district of Norvik. "
        "The text also discusses unrest in neighboring settlements, which is contextual background and not a direct argument.\n"
        "Output:\n"
        "arguments.place += the coastal district of Norvik\n"
        "\n"
        "Example 2:\n"
        "Allowed roles and multiplicities: attacker=1, target=1, instrument=1\n"
        "Extraction notes:\n"
        "The sentence describes an attack scenario. "
        "The attacker is identified as a group of unidentified militants. "
        "The target is a convoy of supply vehicles. "
        "The instrument is described as improvised explosive devices and small arms fire used during the incident. "
        "The text also mentions prior warnings and rising tensions, which are explanatory context and not role arguments.\n"
        "Output:\n"
        "arguments.attacker += a group of unidentified militants\n"
        "arguments.target += a convoy of supply vehicles\n"
        "arguments.instrument += improvised explosive devices and small arms fire used during the incident\n"
        "\n"
        "Example 3:\n"
        "Allowed roles and multiplicities: attacker=1, target=2, place=1\n"
        "Extraction notes:\n"
        "The sentence reports an assault. "
        "The attacker is clearly identified as local militia members. "
        "Two targets are explicitly mentioned: the municipal checkpoint and a nearby storage depot. "
        "The place is given as the eastern edge of Darsin. "
        "The notes also mention public anger after the incident, which is background explanation rather than an argument.\n"
        "Output:\n"
        "arguments.attacker += local militia members\n"
        "arguments.target += the municipal checkpoint\n"
        "arguments.target += a nearby storage depot\n"
        "arguments.place += the eastern edge of Darsin\n"
        "\n"
        "Example 4:\n"
        "Allowed roles and multiplicities: instrument=2, place=1\n"
        "Extraction notes:\n"
        "The sentence refers to a violent confrontation. "
        "Two instruments are explicitly described: hunting rifles and homemade incendiary devices. "
        "The place is stated as a farming village outside Lembat. "
        "The text also includes discussion of longstanding land disputes, which provides context but is not an event argument.\n"
        "Output:\n"
        "arguments.instrument += hunting rifles\n"
        "arguments.instrument += homemade incendiary devices\n"
        "arguments.place += a farming village outside Lembat\n"
        "\n"
        "Example 5:\n"
        "Allowed roles and multiplicities: victim=2, place=1\n"
        "Extraction notes:\n"
        "The sentence implies a deadly incident. "
        "Two victims are clearly mentioned: a senior engineer and his assistant. "
        "The place is identified as a maintenance tunnel beneath the West Ardin plant. "
        "The notes also compare the site to safer facilities elsewhere, which is contrastive context and not part of the event arguments.\n"
        "Output:\n"
        "arguments.victim += a senior engineer\n"
        "arguments.victim += his assistant\n"
        "arguments.place += a maintenance tunnel beneath the West Ardin plant\n"
        "\n"
        "Example 6:\n"
        "Allowed roles and multiplicities: target=1, instrument=1, place=1\n"
        "Extraction notes:\n"
        "The sentence describes a destructive act. "
        "The target is clearly stated as the main transmission tower. "
        "The instrument is not a list of separate arguments; it is given as fuel cans, scrap metal, and wiring assembled into a single device. "
        "The place is identified as an industrial corridor near Pel Sanur. "
        "The text also mentions economic frustration in the area, which is explanatory background and not an event role.\n"
        "Output:\n"
        "arguments.target += the main transmission tower\n"
        "arguments.instrument += fuel cans, scrap metal, and wiring assembled into a single device\n"
        "arguments.place += an industrial corridor near Pel Sanur"
    )
